workflows:
  capacitor-app:
    name: Holy Echoes Codemagic YAML
    max_build_duration: 60
    environment:
      java: 21
      vars:
        PACKAGE_NAME: com.holyechoes.app
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.holyechoes.app
      android_signing:
        - keystore: placelift-upload
          keystore_environment_variable: CM_KEYSTORE_PATH
          keystore_password_environment_variable: CM_KEYSTORE_PASSWORD
          key_alias_environment_variable: CM_KEY_ALIAS
          key_password_environment_variable: CM_KEY_PASSWORD
      node: latest
      cocoapods: default
    scripts:
      - name: Install global and project dependencies
        script: |
          npm install
          npm run build
      - name: Sync web assets with native platforms
        script: |
          npx cap sync
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build Android APK & AAB
        script: |
          cd android
          ./gradlew assembleRelease bundleRelease
      - name: Build iOS IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
                    -scheme App \
                    -configuration Release \
                    -sdk iphoneos \
                    -archivePath $CM_BUILD_OUTPUT_DIR/App.xcarchive \
                    DEVELOPMENT_TEAM=T7T5D9A3KT \
                    CODE_SIGN_STYLE=Manual \
                    CODE_SIGN_IDENTITY="Apple Distribution: Joe Boylson (T7T5D9A3KT)" \
                    PROVISIONING_PROFILE_SPECIFIER="codemagic-asc-provisioning-profile" \
                    -allowProvisioningUpdates \
                    archive

          xcodebuild -exportArchive \
                    -archivePath $CM_BUILD_OUTPUT_DIR/App.xcarchive \
                    -exportOptionsPlist exportOptions.plist \
                    -exportPath $CM_BUILD_OUTPUT_DIR
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - build/*.ipa
      - $CM_BUILD_DIR/build/**/*.ipa
    publishing:
      email:
        recipients:
          - joeboylson@gmail.com
        notify:
          success: true
          failure: true
